"""update

Revision ID: 7dcc1a83baa5
Revises: c59a08d237ff
Create Date: 2024-03-04 22:26:21.724015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcc1a83baa5'
down_revision = 'c59a08d237ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
